#spring.application.name=timesheet
server:
  port: 4444
spring:
  application:
    name: timesheet-page
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true